# Generated by Django 4.0.6 on 2022-07-19 20:57

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220421_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[reviews.validators.year_validator], verbose_name='Год'),
        ),
    ]
